--Find total customers by countries
SELECT 
	country,
	count(distinct(customer_key)) as total_customers 
FROM gold.dim_customers group by country
order by total_customers desc 

--Find total customers by gender
SELECT
	gender,
	count(distinct(customer_key)) as Total_customers
FROM gold.dim_customers
group by gender
order by Total_customers desc

--Find total products by category
SELECT 
	category,
	count(DISTINCT(product_name)) as Total_products
FROM gold.dim_products
group by category
order by Total_products desc

--What is the average costs in each category?
SELECT 
	category,
	avg(product_cost) as avg_costs
FROM gold.dim_products
group by category
order by avg_costs desc

--What is the total revenue generated for each category?
SELECT
	dp.category,
	sum(fs.sales) as Total_revenue
FROM gold.fact_sales fs
LEFT JOIN GOLD.dim_products dp
on	 fs.product_key = dp.product_key
group by dp.category
order by Total_revenue desc

--Find total revenue is generated by each customer
SELECT
	dc.customer_key,
	sum(fs.sales) as Total_revenue
FROM gold.fact_sales fs
LEFT JOIN GOLD.dim_customers dc
on	 fs.customer_key = dc.Customer_primary_key
group by dc.customer_key
order by Total_revenue desc

--What is the distribution of sold items across countries?
SELECT 
	country,
	sum(qunatity) as Distirbution
FROM gold.fact_sales f
left join gold.dim_customers d
on	f.customer_key = d.Customer_primary_key
group by country
order by Distirbution desc